"""Pydantic request/response modellari — domen bo'yicha fayllarga bo'lingan.

Bu paket avvalgi bitta `models/schemas.py` faylining o'rnini bosadi.
Boshqa joylardagi `from models.schemas import X` importlari o'zgarmasdan
ishlayveradi — barcha klasslar shu yerda qayta eksport qilinadi.
"""

from .enums import (
    BuildingUtilityStatus,
    ChatProvider,
    ChatRole,
    DeviceRole,
    FirmwareMode,
    MeasurementRole,
    UtilityType,
)
from .chat import ChatHistoryMessage, ChatRequest
from .buildings import (
    BuildingCreate,
    BuildingCreateResponse,
    BuildingDefaultProvision,
    BuildingDefaultProvisionResponse,
    BuildingDeleteResponse,
    BuildingListResponse,
    BuildingResponse,
    BuildingUpdate,
    BuildingUpdateResponse,
    BuildingUtilityCreate,
    BuildingUtilityCreateResponse,
    BuildingUtilityListResponse,
    BuildingUtilityResponse,
    BuildingUtilityUpdate,
    BuildingUtilityUpdateResponse,
    MeasurementPointCreate,
    MeasurementPointCreateResponse,
    MeasurementPointDeviceBind,
    MeasurementPointListResponse,
    MeasurementPointResponse,
    MeasurementPointUpdate,
    MeasurementPointUpdateResponse,
    PremiseCreate,
    PremiseCreateResponse,
    PremiseListResponse,
    PremiseResponse,
)
from .devices import (
    DeviceConfigEndpointsResponse,
    DeviceConfigIntervalsResponse,
    DeviceConfigResponse,
    DeviceConfigServerResponse,
    DeviceCreate,
    DeviceCreateResponse,
    DeviceListResponse,
    DeviceProvisioningTokenCreate,
    DeviceProvisioningTokenCreateResponse,
    DeviceProvisioningTokenListResponse,
    DeviceProvisioningTokenResponse,
    DeviceProvisioningTokenRevokeResponse,
    DeviceRegister,
    DeviceRegisterResponse,
    DeviceResponse,
    DeviceStatusResponse,
    DeviceTokenResponse,
    DeviceTokenRevokeResponse,
    DeviceUpdate,
    DeviceUpdateResponse,
)
from .firmware import (
    FirmwareCheckResponse,
    FirmwareCompatibilityCreate,
    FirmwareCompatibilityResponse,
    FirmwareInstallEventListResponse,
    FirmwareInstallEventResponse,
    FirmwareListResponse,
    FirmwareOnDemandRequest,
    FirmwareOnDemandResponse,
    FirmwareResponse,
    FirmwareUploadResponse,
    OtaInstallReport,
    OtaReportResponse,
    OTABatchCancelResponse,
    OTABatchCreate,
    OTABatchCreateResponse,
    OTABatchDetailResponse,
    OTABatchDeviceResponse,
    OTABatchListResponse,
    OTABatchProcessResponse,
    OTABatchResponse,
)
from .alerts import (
    AlertListResponse,
    AlertNotificationListResponse,
    AlertNotificationResponse,
    AlertResponse,
    AlertRuleCreate,
    AlertRuleListResponse,
    AlertRuleMutationResponse,
    AlertRuleResponse,
    AlertRuleUpdate,
)
from .common import OkResponse
from .audit import AuditLogListResponse, AuditLogResponse
from .analytics import (
    AnalyticsAggregateResponse,
    BuildingAnalyticsResponse,
    BuildingElectricityAnalyticsResponse,
    BuildingEnergySummaryItem,
    BuildingGasAnalyticsResponse,
    BuildingSoilAnalyticsResponse,
    BuildingSoundAnalyticsResponse,
    BuildingsEnergySummaryResponse,
    BuildingWaterAnalyticsResponse,
    DeviceReadingStatsResponse,
    EnergyBucketResponse,
    EnergyByBuildingResponse,
    HourlyUtilityStatResponse,
    HourlyUtilityStatsResponse,
    SummaryResponse,
)
from .health import HealthResponse, HealthWorkersResponse, ReadyResponse
from .readings import (
    BuildingLatestReadingsResponse,
    BuildingReadingHistoryResponse,
    MeasurementPointLatestResponse,
    MeterReading,
    MeterReadingBatch,
    ReadingBatchErrorResponse,
    ReadingBatchResponse,
    ReadingHistoryResponse,
    ReadingIngestResponse,
    ReadingResponse,
    TestDeviceSimulationRequest,
    TestDeviceSimulationResponse,
)
from .commands import (
    CommandCreate,
    CommandListResponse,
    CommandQueuedResponse,
    CommandResponse,
    DeviceStatus,
    PendingCommandListResponse,
    PendingCommandResponse,
)
from .backups import (
    BackupCleanupResponse,
    BackupCreateResponse,
    BackupDeleteResponse,
    BackupInfo,
    BackupListResponse,
    BackupRestoreResponse,
)
from .external_forward import (
    ExternalForwardCreate,
    ExternalForwardResponse,
    ExternalForwardTestResponse,
    ExternalForwardUpdate,
)

__all__ = [
    # enums
    "BuildingUtilityStatus",
    "ChatProvider",
    "ChatRole",
    "DeviceRole",
    "FirmwareMode",
    "MeasurementRole",
    "UtilityType",
    # chat
    "ChatHistoryMessage",
    "ChatRequest",
    # buildings
    "BuildingCreate",
    "BuildingCreateResponse",
    "BuildingDefaultProvision",
    "BuildingDefaultProvisionResponse",
    "BuildingDeleteResponse",
    "BuildingListResponse",
    "BuildingResponse",
    "BuildingUpdate",
    "BuildingUpdateResponse",
    "BuildingUtilityCreate",
    "BuildingUtilityCreateResponse",
    "BuildingUtilityListResponse",
    "BuildingUtilityResponse",
    "BuildingUtilityUpdate",
    "BuildingUtilityUpdateResponse",
    "MeasurementPointCreate",
    "MeasurementPointCreateResponse",
    "MeasurementPointDeviceBind",
    "MeasurementPointListResponse",
    "MeasurementPointResponse",
    "MeasurementPointUpdate",
    "MeasurementPointUpdateResponse",
    "PremiseCreate",
    "PremiseCreateResponse",
    "PremiseListResponse",
    "PremiseResponse",
    # devices
    "DeviceConfigEndpointsResponse",
    "DeviceConfigIntervalsResponse",
    "DeviceConfigResponse",
    "DeviceConfigServerResponse",
    "DeviceCreate",
    "DeviceCreateResponse",
    "DeviceListResponse",
    "DeviceProvisioningTokenCreate",
    "DeviceProvisioningTokenCreateResponse",
    "DeviceProvisioningTokenListResponse",
    "DeviceProvisioningTokenResponse",
    "DeviceProvisioningTokenRevokeResponse",
    "DeviceRegister",
    "DeviceRegisterResponse",
    "DeviceResponse",
    "DeviceStatusResponse",
    "DeviceTokenResponse",
    "DeviceTokenRevokeResponse",
    "DeviceUpdate",
    "DeviceUpdateResponse",
    # firmware / OTA
    "FirmwareCheckResponse",
    "FirmwareCompatibilityCreate",
    "FirmwareCompatibilityResponse",
    "FirmwareInstallEventListResponse",
    "FirmwareInstallEventResponse",
    "FirmwareListResponse",
    "FirmwareOnDemandRequest",
    "FirmwareOnDemandResponse",
    "FirmwareResponse",
    "FirmwareUploadResponse",
    "OtaInstallReport",
    "OtaReportResponse",
    "OTABatchCancelResponse",
    "OTABatchCreate",
    "OTABatchCreateResponse",
    "OTABatchDetailResponse",
    "OTABatchDeviceResponse",
    "OTABatchListResponse",
    "OTABatchProcessResponse",
    "OTABatchResponse",
    # alerts
    "AlertListResponse",
    "AlertNotificationListResponse",
    "AlertNotificationResponse",
    "AlertResponse",
    "AlertRuleCreate",
    "AlertRuleListResponse",
    "AlertRuleMutationResponse",
    "AlertRuleResponse",
    "AlertRuleUpdate",
    # common
    "OkResponse",
    # audit
    "AuditLogListResponse",
    "AuditLogResponse",
    # analytics
    "AnalyticsAggregateResponse",
    "BuildingAnalyticsResponse",
    "BuildingElectricityAnalyticsResponse",
    "BuildingEnergySummaryItem",
    "BuildingGasAnalyticsResponse",
    "BuildingSoilAnalyticsResponse",
    "BuildingSoundAnalyticsResponse",
    "BuildingsEnergySummaryResponse",
    "BuildingWaterAnalyticsResponse",
    "DeviceReadingStatsResponse",
    "EnergyBucketResponse",
    "EnergyByBuildingResponse",
    "HourlyUtilityStatResponse",
    "HourlyUtilityStatsResponse",
    "SummaryResponse",
    # health
    "HealthResponse",
    "HealthWorkersResponse",
    "ReadyResponse",
    # readings
    "BuildingLatestReadingsResponse",
    "BuildingReadingHistoryResponse",
    "MeasurementPointLatestResponse",
    "MeterReading",
    "MeterReadingBatch",
    "ReadingBatchErrorResponse",
    "ReadingBatchResponse",
    "ReadingHistoryResponse",
    "ReadingIngestResponse",
    "ReadingResponse",
    "TestDeviceSimulationRequest",
    "TestDeviceSimulationResponse",
    # commands
    "CommandCreate",
    "CommandListResponse",
    "CommandQueuedResponse",
    "CommandResponse",
    "DeviceStatus",
    "PendingCommandListResponse",
    "PendingCommandResponse",
    # backups
    "BackupCleanupResponse",
    "BackupCreateResponse",
    "BackupDeleteResponse",
    "BackupInfo",
    "BackupListResponse",
    "BackupRestoreResponse",
    # external forward
    "ExternalForwardCreate",
    "ExternalForwardResponse",
    "ExternalForwardTestResponse",
    "ExternalForwardUpdate",
]
